USE hr;
SELECT J.JOB_ID, (ROUND(AVG(E.SALARY), 2)) AS MEAN_SALARY, J.JOB_TITLE
  FROM employees AS E
  INNER JOIN jobs as J
  WHERE J.JOB_ID = E.JOB_ID
  GROUP BY E.JOB_ID
  ORDER BY MEAN_SALARY DESC
;
